export default {
    products: [
        {
            _id: '001',
        name: 'Bread',
        category: 'bakery',
        Image: '/Photos/products/bread.jpg',
        price: 1.00,
        brand: 'Co-Op',
        rating: 4.00,
        NumReviews: 5,
        countInStock:10,
    },
    {
        _id: '002',
        name: 'Coca-cola',
        category: 'softdrinks',
        Image: 'Photos/products/coca-cola.jpg',
        price: 1.29,
        brand: 'coke',
        rating: 3.9,
        NumReviews: 8,
        countInStock:6,
    },
    {
        _id: '003',
        name: 'Chicken',
        category: 'Meat',
        Image: '/Photos/products/bread.jpg',
        price: 3.00,
        brand: 'Co-Op',
        rating: 4.7,
        NumReviews: 9,
        countInStock:6,
    },
    {
        _id: '004',
        name: 'DairyMilk',
        category: 'chocolate',
        Image: '/Photos/products/bread.jpg',
        price: 1.00,
        brand: 'DairyMilk',
        rating: 4.0,
        NumReviews: 8,
        countInStock:6,
    },
    {
        _id: '005',
        name: 'Milk',
        category: 'chilled',
        Image: '/Photos/products/bread.jpg',
        price: 1.49,
        brand: 'Grahams',
        rating: 4.3,
        NumReviews: 4,
        countInStock:6,
    },
    {
        _id: '005',
        name: 'Cereal',
        category: 'chilled',
        Image: '/Photos/products/bread.jpg',
        price: 1.49,
        brand: 'Grahams',
        rating: 4.3,
        NumReviews: 4,
        countInStock:6,
    },
    {
        _id: '005',
        name: 'Milk',
        category: 'chilled',
        Image: '/Photos/products/bread.jpg',
        price: 1.49,
        brand: 'Grahams',
        rating: 4.3,
        NumReviews: 4,
        countInStock:6,
    },
    {
        _id: '005',
        name: 'Milk',
        category: 'chilled',
        Image: '/Photos/products/bread.jpg',
        price: 1.49,
        brand: 'Grahams',
        rating: 4.3,
        NumReviews: 4,
        countInStock:6,
    },
    {
        _id: '005',
        name: 'Milk',
        category: 'chilled',
        Image: '/Photos/products/bread.jpg',
        price: 1.49,
        brand: 'Grahams',
        rating: 4.3,
        NumReviews: 4,
        countInStock:6,
    },
    {
        _id: '005',
        name: 'Milk',
        category: 'chilled',
        Image: '/Photos/products/bread.jpg',
        price: 1.49,
        brand: 'Grahams',
        rating: 4.3,
        NumReviews: 4,
        countInStock:6,
    },
    {
        _id: '005',
        name: 'Milk',
        category: 'chilled',
        Image: '/Photos/products/bread.jpg',
        price: 1.49,
        brand: 'Grahams',
        rating: 4.3,
        NumReviews: 4,
        countInStock:6,
    },
    {
        _id: '005',
        name: 'Milk',
        category: 'chilled',
        Image: '/Photos/products/bread.jpg',
        price: 1.49,
        brand: 'Grahams',
        rating: 4.3,
        NumReviews: 4,
        countInStock:6,
    },
       {
        _id: '005',
        name: 'Milk',
        category: 'chilled',
        Image: '/Photos/products/bread.jpg',
        price: 1.49,
        brand: 'Grahams',
        rating: 4.3,
        NumReviews: 4
    }
]
}