export default {
    products: [
        {
            _id: '001',
        name: 'Bread',
        category: 'bakery',
        Image: '/Photos/products/bread.jpg',
        price: 1.00,
        brand: 'Co-Op',
        Description: 'This is a white co op bread',
        rating: 4.00,
        NumReviews: 5,
        countInStock:10,
    },
    {
        _id: '002',
        name: 'Coca-cola',
        category: 'softdrinks',
        Image: '/Photos/products/coke.jpg',
        price: 1.29,
        brand: 'coke',
        rating: 3.9,
        NumReviews: 8,
        countInStock:6,
    },
    {
        _id: '003',
        name: 'Apple',
        category: 'Fruit',
        Image: '/Photos/products/apple.jpg',
        price: 3.00,
        brand: 'Co-Op',
        rating: 4.7,
        NumReviews: 9,
        countInStock:6,
    },
    {
        _id: '004',
        name: 'DairyMilk',
        category: 'chocolate',
        Image: '/Photos/products/dairymilk.jpeg',
        price: 1.00,
        brand: 'DairyMilk',
        rating: 4.0,
        NumReviews: 8,
        countInStock:6,
    },
    {
        _id: '005',
        name: 'Milk',
        category: 'chilled',
        Image: '/Photos/products/milk.jpg',
        price: 1.49,
        brand: 'Grahams',
        rating: 4.3,
        NumReviews: 4,
        countInStock:6,
    },
    {
        _id: '006',
        name: 'Cereal',
        category: 'chilled',
        Image: '/Photos/products/cereal.jpg',
        price: 3.00,
        brand: 'Oreo',
        rating: 4.3,
        NumReviews: 4,
        countInStock:6,
    },
    {
        _id: '007',
        name: 'Butter',
        category: 'chilled',
        Image: '/Photos/products/butter.jpg',
        price: 2.49,
        brand: 'Lurpark',
        rating: 4.3,
        NumReviews: 4,
        countInStock:6,
    },

]
}